### ISSUE TITLE
Title cell exapanded should collapse as user clicked on an other Tile cell section

### ISSUE THREAD

**Issue by naeemdevClan** [narciero/NAExpandableTableController#1]
Only one cell should be expandable at a time while other are collasped

**Comment by narciero** [comment]
I have added a new property to NAExpandableTableController to indicate whether you'd like to enforce only 1 cell being expanded at a time. Just add the following line of code:

`expandableTableController.exclusiveExpand = true`

Let me know if you have any other issues.

**Comment by naeemdevClan** [comment]
@narciero Thanks, It is working now.
